site_name: My Docs
repo_url: https://github.com/zerenxyz/mkdocs-material-plugin.git
theme:
  name: material

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
